"""Add AccionProveedor and update Proveedor

Revision ID: 5725bba3e2fd
Revises: 002
Create Date: 2026-02-12 20:05:40.502277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5725bba3e2fd'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Crear el tipo ENUM primero
    categoriaproveedor = postgresql.ENUM('MATERIALES', 'MANO_DE_OBRA', 'SERVICIOS', 'EQUIPAMIENTO', 'OTROS', name='categoriaproveedor', create_type=False)
    categoriaproveedor.create(op.get_bind(), checkfirst=True)

    # Agregar columna categoria con valor por defecto
    op.add_column('proveedores', sa.Column('categoria', sa.Enum('MATERIALES', 'MANO_DE_OBRA', 'SERVICIOS', 'EQUIPAMIENTO', 'OTROS', name='categoriaproveedor', create_type=False), nullable=False, server_default='OTROS'))
    op.alter_column('proveedores', 'categoria', server_default=None)

    # Agregar nuevas columnas
    op.add_column('proveedores', sa.Column('calificacion', sa.Integer(), nullable=True))
    op.add_column('proveedores', sa.Column('total_pagado', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('proveedores', sa.Column('total_pendiente', sa.Numeric(precision=15, scale=2), nullable=True))

    # Eliminar columnas que existen en la migración inicial (001)
    op.drop_column('proveedores', 'calificacion_servicio')
    op.drop_column('proveedores', 'calificacion_calidad')
    op.drop_column('proveedores', 'calificacion_general')
    op.drop_column('proveedores', 'tipo')
    op.drop_column('proveedores', 'calificacion_precio')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'unidades', type_='foreignkey')
    op.alter_column('unidades', 'notas',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('unidades', 'estacionamientos',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=0),
               existing_nullable=True)
    op.alter_column('unidades', 'habitaciones',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=0),
               existing_nullable=True)
    op.alter_column('unidades', 'caracteristicas',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('unidades', 'descripcion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('unidades', 'avance_porcentaje',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('proveedores', sa.Column('calificacion_precio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('volumen_compra_anual', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('tipo', postgresql.ENUM('MATERIALES', 'SERVICIOS', 'AMBOS', name='tipoproveedor'), autoincrement=False, nullable=False))
    op.add_column('proveedores', sa.Column('calificacion_general', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('calificacion_calidad', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('proveedores', sa.Column('calificacion_servicio', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('proveedores', 'total_pendiente')
    op.drop_column('proveedores', 'total_pagado')
    op.drop_column('proveedores', 'calificacion')
    op.drop_column('proveedores', 'categoria')
    # ### end Alembic commands ###
